name: Test Bash

on:
  push:
    paths:
      - 'Bash/**'
      - '.github/workflows/Bash.yml'
  pull_request:
    paths:
      - 'Bash/**'
      - '.github/workflows/Bash.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up dependencies
      working-directory: Bash
      run: |
        wget -nv https://github.com/SamirTalwar/smoke/releases/download/v2.3.0/smoke-v2.3.0-Linux-x86_64
        chmod 755 smoke-v2.3.0-Linux-x86_64
        mv smoke-v2.3.0-Linux-x86_64 smoke

    - name: Test
      working-directory: Bash
      run: |
        export PATH=$PATH:$(pwd)
        ./run_tests.sh

    - name: Report using branch name (dynamic, use for a pair on each branch)
      run: |
        export GIT_BRANCH_NAME=$(git symbolic-ref --short HEAD)
        export GIT_BRANCH_NAME=$( echo "$GIT_BRANCH_NAME" | sed 's/ /%20/g' )
        curl -X GET ${{ secrets.PUSH_COUNTER_URL }}/record/$GIT_BRANCH_NAME?build=green
