name: Test C

on:
  push:
    paths:
      - 'C/**'
      - '.github/workflows/C.yml'
  pull_request:
    paths:
      - 'C/**'
      - '.github/workflows/C.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libcmocka-dev

    - name: Build
      working-directory: C
      run: gcc -std=c99 Parrot.c ParrotTest.c -l cmocka -o ParrotTest

    - name: Test
      working-directory: C
      run: ./ParrotTest

    - name: Report using branch name (dynamic, use for a pair on each branch)
      run: |
        export GIT_BRANCH_NAME=$(git symbolic-ref --short HEAD)
        export GIT_BRANCH_NAME=$( echo "$GIT_BRANCH_NAME" | sed 's/ /%20/g' )
        curl -X GET ${{ secrets.PUSH_COUNTER_URL }}/record/$GIT_BRANCH_NAME?build=green
