name: Test Clojure

on:
  push:
    paths:
      - 'Clojure/**'
      - '.github/workflows/Clojure.yml'
  pull_request:
    paths:
      - 'Clojure/**'
      - '.github/workflows/Clojure.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@3.2
      with:
          lein: latest
    - name: Cache lein
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-lein-${{ hashFiles('Clojure/project.clj') }}
        restore-keys: ${{ runner.os }}-lein

    - name: Build and test
      working-directory: Clojure
      run: lein midje

    - name: Report using branch name (dynamic, use for a pair on each branch)
      run: |
        export GIT_BRANCH_NAME=$(git symbolic-ref --short HEAD)
        export GIT_BRANCH_NAME=$( echo "$GIT_BRANCH_NAME" | sed 's/ /%20/g' )
        curl -X GET ${{ secrets.PUSH_COUNTER_URL }}/record/$GIT_BRANCH_NAME?build=green
