name: Test Crystal

on:
  push:
    paths:
      - 'Crystal/**'
      - '.github/workflows/Crystal.yml'
  pull_request:
    paths:
      - 'Crystal/**'
      - '.github/workflows/Crystal.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Crystal
      uses: oprypin/install-crystal@v1

    - name: Test
      working-directory: Crystal
      run: crystal spec

    - name: Report using branch name (dynamic, use for a pair on each branch)
      run: |
        export GIT_BRANCH_NAME=$(git symbolic-ref --short HEAD)
        export GIT_BRANCH_NAME=$( echo "$GIT_BRANCH_NAME" | sed 's/ /%20/g' )
        curl -X GET ${{ secrets.PUSH_COUNTER_URL }}/record/$GIT_BRANCH_NAME?build=green
