name: Test CSharp

on:
  push:
    paths:
      - 'CSharp/**'
      - '.github/workflows/CSharp.yml'
  pull_request:
    paths:
      - 'CSharp/**'
      - '.github/workflows/CSharp.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.x

    - name: Set up dependencies
      working-directory: CSharp
      run: dotnet restore

    - name: Build
      working-directory: CSharp
      run: dotnet build --no-restore

    - name: Test
      working-directory: CSharp
      run: dotnet test --no-build --verbosity normal

    - name: Report using branch name (dynamic, use for a pair on each branch)
      run: |
        export GIT_BRANCH_NAME=$(git symbolic-ref --short HEAD)
        export GIT_BRANCH_NAME=$( echo "$GIT_BRANCH_NAME" | sed 's/ /%20/g' )
        curl -X GET ${{ secrets.PUSH_COUNTER_URL }}/record/$GIT_BRANCH_NAME?build=green
