name: Test Ruby

on:
  push:
    paths:
      - 'Ruby/**'
      - '.github/workflows/Ruby.yml'
  pull_request:
    paths:
      - 'Ruby/**'
      - '.github/workflows/Ruby.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.3

    - name: Set up dependencies
      working-directory: Ruby
      run: |
        gem install bundler
        bundle install

    - name: Test
      working-directory: Ruby
      run: rake

    - name: Report using branch name (dynamic, use for a pair on each branch)
      run: |
        export GIT_BRANCH_NAME=$(git symbolic-ref --short HEAD)
        export GIT_BRANCH_NAME=$( echo "$GIT_BRANCH_NAME" | sed 's/ /%20/g' )
        curl -X GET ${{ secrets.PUSH_COUNTER_URL }}/record/$GIT_BRANCH_NAME?build=green
