name: Swift Test

on: 
  push:
    paths:
      - 'Swift/**'
      - '.github/workflows/Swift.yml'
  pull_request:
    paths:
      - 'Swift/**'
      - '.github/workflows/Swift.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout Project
        uses: actions/checkout@v2
      - name: Setup Swift
        uses: fwal/setup-swift@master
        with:
          swift-version: "5.5"
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
      - name: Clean up
        run: rm -rf .build/
