name: Swift Test

on: 
  push:
    paths:
      - 'Swift/**'
      - '.github/workflows/Swift.yml'
  pull_request:
    paths:
      - 'Swift/**'
      - '.github/workflows/Swift.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout Project
        uses: actions/checkout@v2
      - name: Setup Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: "5.5"
      - name: display Version
        run: |
          swift --version
          pwd
      - name: Build
        working-directory: Swift
        run: |
          pwd
          swift build
      - name: Run tests
        working-directory: Swift
        run: swift test
      - name: Clean up
        run: rm -rf Swift/.build
