name: Test Swift

on:
  push:
    paths:
      - 'Swift/**'
      - '.github/workflows/Swift.yml'
  pull_request:
    paths:
      - 'Swift/**'
      - '.github/workflows/Swift.yml'

jobs:
  test:
    name: Build and Test
    strategy:
      matrix:
        swift: [5.5]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: ${{ matrix.swift }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: xcodebuild clean build -workspace "project.xcworkspace"

    - name: Run tests
      run: xcodebuild clean test -workspace "project.xcworkspace"
